import type { Permission } from "./permissions"

export const routePermissions: Record<string, Permission> = {
  "/": "dashboard.view",
  "/chamados": "chamados.view",
  "/chamados/ure": "chamados.ure.create",
  "/chamados/escola": "chamados.escola.create",
  "/gestao-chamados": "gestaoChamados.view",
  "/escolas": "escolas.view",
  "/usuarios": "usuarios.view",
  "/relatorios": "relatorios.view",
  "/gestao-escolas":"escolas.manage",
  "/dashboard-escolar":"dashboard.escolar",
  "/fields":"fields.view",
  "/fields/agenda-field":"agenda.field",
  "/fields/inteligencia-operacional":"intoperacional.field",
  "/inventario":"inventario.view",
  "/inventario/visao-geral":"inventario.vgeral",
  "/apoio-usuario":"apoio.usuario",
  "/tutoriais-populares":"tutoriais.populares",
  "/painel-chamados":"painel.chamados",
  "/avisos":"avisos.view",
  "/toners":"toners.view",
  "/toners/entrada":"toners.entrada",
  "/toners/saida":"toners.saida",
  "/toners/movimentacoes":"toners.historico",
  "/edumonitor":"edu.monitor",
  "/segundo-link":"segundo.link",
  "/fields/avaliacoes":"avaliacoes.field",
  "/gestao-equipamentos":"gestao.equipamentos",
  "/fields/demandas":"fields.demandas",
  "/fields/setorizacao":"fields.setorizacao",
  "/fields/painel-setorizacao":"fields.painel",
  "/fields/mapa-field":"fields.mapa",
  "/fields/relatorio-tecnico":"fields.relatorio"
}